name: partly_windy
description: A weather app powered by the very latest in machine learning technology.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Adds support and Widgets for Wear OS devices
  wear: ^1.1.0
  # Used to make network calls
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
